# https://github.com/actions/labeler#common-examples
# Adapted from https://github.com/rapidsai/cugraph/blob/main/.github/CODEOWNERS
# Labels culled from https://github.com/rapidsai/cugraph/labels

python:
  - 'python/**'
  - 'notebooks/**'
  - 'benchmarks/**'
  
doc:
  - 'docs/**'
  - '**/*.md'
  
datasets:
  - 'datasets/**'
  
cpp:
  - 'cpp/**'

CMake:
  - '**/CMakeLists.txt'
  - '**/cmake/**'

conda:
  - 'conda/**'

ci:
  - 'ci/**'

github: 
   - '.github/**'
  
docker:
  - '**/Dockerfile'
  - '**/.dockerignore'
  - 'docker/**'
